name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none


environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  envied_flutter: ^0.3.0

dev_dependencies:
  flutter:
    sdk: flutter

  build_runner:
  envied_flutter_generator: ^0.3.0
  lints: ^2.0.0
  test: ^1.16.0


dependency_overrides:
  envied_flutter:
    path: ../../packages/envied

  envied_flutter_generator:
    path: ../../packages/envied_generator
